-- CarbonLens SME - Traceable Emission Factors & Seed Data

INSERT INTO emission_factors (id, category, activity_type, sub_type, source_name, factor_value, factor_unit, source_organization, document_reference, reference_year, notes)
VALUES
('ef_virgin_hdpe', 'materials', 'HDPE', 'virgin', 'Virgin HDPE Polymer Feedstock', 1.9300, 'kgCO2e/kg', 'CPCB / Ecoinvent', 'Ecoinvent 3.9 Database & CPCB Polymer LCA Guidelines', 2023, 'Granule feedstock production embodied carbon'),
('ef_virgin_ldpe', 'materials', 'LDPE', 'virgin', 'Virgin LDPE Polymer Feedstock', 2.0800, 'kgCO2e/kg', 'CPCB / Ecoinvent', 'Ecoinvent 3.9 Database & CPCB Polymer LCA Guidelines', 2023, 'Film-grade resin production embodied carbon'),
('ef_virgin_pp', 'materials', 'PP', 'virgin', 'Virgin PP Polymer Feedstock', 1.9800, 'kgCO2e/kg', 'CPCB / Ecoinvent', 'Ecoinvent 3.9 Database & CPCB Polymer LCA Guidelines', 2023, 'Molding and woven sack resin feedstock'),
('ef_virgin_pet', 'materials', 'PET', 'virgin', 'Virgin PET Polymer Feedstock', 2.1500, 'kgCO2e/kg', 'CPCB / Ecoinvent', 'Ecoinvent 3.9 Database & CPCB Polymer LCA Guidelines', 2023, 'Bottle & sheet grade PET resin'),
('ef_recycled_hdpe', 'materials', 'HDPE', 'recycled', 'Recycled HDPE (Post-Consumer PCR)', 0.5800, 'kgCO2e/kg', 'Plastics Recyclers India / APR', 'APR Post-Consumer Resin LCA Study', 2022, 'Washed and re-pelletized PCR resin'),
('ef_recycled_ldpe', 'materials', 'LDPE', 'recycled', 'Recycled LDPE (Post-Consumer PCR)', 0.6200, 'kgCO2e/kg', 'Plastics Recyclers India / APR', 'APR Post-Consumer Resin LCA Study', 2022, 'Recycled film-grade PCR pellets'),
('ef_recycled_pp', 'materials', 'PP', 'recycled', 'Recycled PP (Post-Consumer PCR)', 0.5500, 'kgCO2e/kg', 'Plastics Recyclers India / APR', 'APR Post-Consumer Resin LCA Study', 2022, 'Recycled PP regrind / pellets'),
('ef_recycled_pet', 'materials', 'PET', 'recycled', 'Recycled PET (Post-Consumer rPET)', 0.6800, 'kgCO2e/kg', 'Plastics Recyclers India / APR', 'APR Post-Consumer Resin LCA Study', 2022, 'rPET flakes / regrind'),
('ef_grid_electricity', 'energy', 'grid_electricity', 'grid', 'Indian National Grid Electricity', 0.7160, 'kgCO2e/kWh', 'Central Electricity Authority (CEA)', 'CO2 Baseline Database for the Indian Power Sector, Version 19', 2023, 'Grid weighted average emission factor including T&D losses'),
('ef_fuel_diesel', 'energy', 'diesel', 'fuel', 'High Speed Diesel Fuel', 2.6870, 'kgCO2e/liter', 'IPCC', '2006 IPCC Guidelines for National Greenhouse Gas Inventories', 2006, 'Stationary combustion of commercial diesel'),
('ef_fuel_png', 'energy', 'natural_gas', 'fuel', 'Piped Natural Gas (PNG)', 1.9200, 'kgCO2e/m3', 'GSPC / Gujarat Gas & IPCC', 'IPCC Stationary Combustion Guidelines & Industrial Gas Benchmarks', 2021, 'Industrial fuel gas combustion'),
('ef_waste_landfill', 'waste', 'landfill', 'disposal', 'Plastic Waste to Landfill', 1.4500, 'kgCO2e/kg', 'CPCB / UK DEFRA', 'CPCB Municipal Solid Waste Guidelines & DEFRA Waste Factors', 2022, 'Unmanaged disposal of mixed polymer scrap'),
('ef_waste_incineration', 'waste', 'incineration', 'disposal', 'Plastic Waste to Incineration', 1.2000, 'kgCO2e/kg', 'IPCC / CPCB', '2006 IPCC Guidelines for Waste Incineration', 2006, 'Thermal destruction without energy recovery'),
('ef_waste_recycling', 'waste', 'recycled', 'circular', 'Plastic Scrap Diverted to Recycling', 0.1000, 'kgCO2e/kg', 'CPCB / APR', 'CPCB Circular Waste Management Benchmarks', 2022, 'Sorting and mechanical processing transport')
ON CONFLICT (id) DO NOTHING;

INSERT INTO recyclers_vendors (id, name, partner_type, materials_supported, location, distance_km, contact_info, notes, is_demo)
VALUES
('partner_ecoplast_vatva', 'Ecoplast Solutions Pvt Ltd', 'Mechanical Recycler & Pelletizer', ARRAY['HDPE', 'PP', 'LDPE'], 'Vatva GIDC, Ahmedabad, Gujarat', 4.2, 'Phone: +91 98250 12345 | Email: info@ecoplastsolutions.in', 'Specializes in washed HDPE/PP regrind pellets and film scrap processing.', TRUE),
('partner_gujarat_polymers_naroda', 'Gujarat Polymers Circular Hub', 'Rigid Plastic Washing & Flaking', ARRAY['HDPE', 'PP', 'PET'], 'Naroda GIDC, Ahmedabad, Gujarat', 14.8, 'Phone: +91 98795 67890 | Email: contact@gujaratpolymers.com', 'GPCB registered collector & flaker for rigid polymer scrap.', TRUE),
('partner_green_vatva', 'GreenVatva Regrind & Compounding', 'Toll Granulation & Granulator Supplier', ARRAY['HDPE', 'LDPE', 'LLDPE'], 'Phase IV, Vatva GIDC, Ahmedabad', 5.1, 'Phone: +91 94260 55443 | Email: sales@greenvatva.in', 'Provides beside-the-press granulator equipment and toll grinding services.', TRUE),
('partner_sanand_ecopellets', 'Sanand EcoPellets Industries', 'PCR Pellet Supplier', ARRAY['PP', 'HDPE', 'PET'], 'Sanand GIDC II, Gujarat', 28.5, 'Phone: +91 99099 88123 | Email: orders@sanandecopellets.com', 'Supplies certified post-consumer recycled pellets (rPP, rHDPE, rPET).', TRUE),
('partner_changodar_recovery', 'Changodar Plastic Recovery Corp', 'Film Scrap Offtake & EPR Partner', ARRAY['LDPE', 'LLDPE', 'BOPP'], 'Changodar Industrial Zone, Ahmedabad', 19.3, 'Phone: +91 98244 33211 | Email: connect@changodarcircular.com', 'Aggregates flexible film scrap under CPCB EPR registration framework.', TRUE),
('partner_shreeji_solar', 'Shreeji CleanTech Solar & EPC', 'Rooftop Solar & Energy EPC', ARRAY['Solar PV', 'Net Metering', 'VFD Drives'], 'Odhav GIDC, Ahmedabad, Gujarat', 9.5, 'Phone: +91 98980 11223 | Email: projects@shreejisolar.in', 'Turnkey rooftop solar installations and energy audit services for MSMEs.', TRUE),
('partner_vadodara_ecopolymers', 'Vadodara Circular Polymer Hub', 'Mechanical Recycler & Toll Compounding', ARRAY['HDPE', 'PP', 'LDPE'], 'Makarpura GIDC, Vadodara, Gujarat', 3.5, 'Phone: +91 98251 77665 | Email: info@vadodarapolymers.in', 'Specializes in rigid polymer scrap flaking & compounding for Central Gujarat industrial belt.', TRUE),
('partner_ankleshwar_clean', 'Ankleshwar Industrial Circular Waste Corp', 'Hazardous & Polymer Recovery Unit', ARRAY['HDPE', 'PP', 'Industrial Scrap'], 'Ankleshwar GIDC, Bharuch, Gujarat', 12.0, 'Phone: +91 98252 88990 | Email: recycle@ankleshwarcircular.in', 'Authorized GPCB partner for industrial polymer scrap & chemical container recycling.', TRUE),
('partner_surat_sachin_polymers', 'Surat Sachin PCR Granulation Hub', 'Film & Woven Scrap Recycler', ARRAY['LDPE', 'LLDPE', 'PP'], 'Sachin GIDC, Surat, Gujarat', 8.4, 'Phone: +91 98791 44332 | Email: sales@sachinpcr.com', 'Large-scale pelletizer for flexible film scrap & packaging waste across South Gujarat.', TRUE),
('partner_rajkot_metoda_regrind', 'Rajkot Metoda Engineering Regrind Hub', 'Rigid Molded Scrap Recycler', ARRAY['PP', 'HDPE', 'ABS'], 'Metoda GIDC, Rajkot, Gujarat', 6.8, 'Phone: +91 94272 11009 | Email: contact@metodaregrind.in', 'Toll granulator serving Saurashtra auto-ancillary & rigid molding units.', TRUE),
('partner_vapi_circular_pack', 'Vapi Paper & Polymer Circular Recovery', 'Multi-Layer Packaging Recycler', ARRAY['PET', 'LDPE', 'Laminated Packaging'], 'Vapi GIDC, Valsad, Gujarat', 15.2, 'Phone: +91 98240 66554 | Email: info@vapicircular.org', 'Specializes in multi-layer flexible barrier scrap & paper-poly foil separation.', TRUE),
('partner_halol_polypellets', 'Halol Auto-Polymer PCR Compounding', 'Engineering Polymer Compounder', ARRAY['PP', 'HDPE', 'PET'], 'Halol GIDC, Panchmahal, Gujarat', 11.5, 'Phone: +91 99044 33221 | Email: ops@halolcompounding.in', 'Compounding facility converting automotive plastic scrap into reinforced PCR granules.', TRUE)
ON CONFLICT (id) DO NOTHING;
